### Nom de l'application obligatoire, sinon ReleaseName+chartName

resources: {}

ingress:
  enabled: false
  className: "public-iks-k8s-nginx"
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-stag-http01
    # cert-manager.io/cluster-issuer: letsencrypt-prod-http01
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
